services:
  init:
    build:
      context: .
  database-init:
    build:
      context: .
  app:
    build:
      context: .
  worker:
    build:
      context: .
  scheduler:
    build:
      context: .
