import i18n from 'i18next';
import { initReactI18next, useTranslation } from 'react-i18next';
import { router } from '@inertiajs/react';

export const localeCodes = ['en', 'pt_BR', 'es'] as const;
export type LocaleCode = (typeof localeCodes)[number];

export const resources = {
  en: { translation: {
    'language.change': 'Change language', 'language.updating': 'Changing language', 'common.back': 'Back to projects', 'common.create': 'Create', 'common.status': 'Status',
    'welcome.title': 'Migrate your IPAM safely.', 'welcome.body': 'Discover, map, review and apply a phpIPAM → NetBox migration with an auditable plan.', 'welcome.setup': 'Set up installation', 'welcome.login': 'Sign in',
    'setup.title': 'Claim installation', 'setup.help': 'Use the token shown by', 'setup.token': 'Token', 'setup.name': 'Name', 'setup.email': 'Email', 'setup.password': 'Password', 'setup.password_help': '14–128 characters, with uppercase, lowercase, number and symbol.', 'setup.confirm': 'Confirm password', 'setup.submit': 'Create owner',
    'login.title': 'Sign in to IpamFerry', 'login.submit': 'Sign in', 'dashboard.title': 'Migration projects', 'dashboard.new': 'New project', 'dashboard.empty': 'Create a project to start discovery.', 'dashboard.plans': '{{count}} plan(s) generated',
    'projects.new': 'New project', 'projects.name': 'Name', 'projects.source': 'Source', 'projects.existing': 'Existing projects', 'projects.api': 'phpIPAM API', 'projects.dump': 'SQL mysqldump', 'projects.locale': 'Artifact language',
    'show.import': '1. Import mysqldump', 'show.sql_safe': 'SQL is parsed and never executed.', 'show.dump_file': 'SQL dump', 'show.read_dump': 'Read dump', 'show.discover': '1. Discover APIs', 'show.tokens_safe': 'Tokens are held only in browser and request memory.', 'show.run_discovery': 'Run discovery', 'show.plan_apply': '4. Review, approve and apply', 'show.generate_plan': 'Generate plan', 'show.actions_conflicts': '{{actions}} actions, {{conflicts}} conflicts', 'show.mapping_warning': '{{type}} requires mapping review before export to NetBox.', 'show.confirm_apply': 'I confirm applying this exact approved plan', 'show.apply': 'Apply through API', 'show.bundle': 'Download audit bundle', 'show.netbox_url': 'NetBox URL', 'show.netbox_token': 'NetBox token', 'show.phpipam_url': 'phpIPAM URL', 'show.phpipam_app': 'App ID', 'show.phpipam_token': 'phpIPAM token',
    'show.inventory': '2. Canonical inventory', 'show.inventory_empty': 'Run discovery to build the sanitized canonical inventory.', 'show.mapping': '3. Mapping policy', 'show.mapping_help': 'Choose the artifact language and edit the versioned, non-executable mapping policy.', 'show.mapping_json': 'Mapping JSON', 'show.save_mapping': 'Save mapping', 'show.plan_help': 'Planning is read-only. Conflicts prevent approval and apply.', 'show.planning': 'Planning…', 'show.conflicts': 'Blocking conflicts', 'show.actions': 'Planned actions', 'show.operation': 'Operation', 'show.source': 'Source', 'show.target': 'NetBox target', 'show.identity': 'Natural key', 'show.confirm_approve': 'I reviewed the diff and approve this exact fingerprint', 'show.approve': 'Approve plan', 'show.applying': 'Applying batch…', 'show.resume': 'Resume apply', 'show.execution': 'Execution #{{id}}', 'show.progress': '{{completed}} of {{total}} actions completed', 'show.verify': '5. Verify target state', 'show.verifying': 'Verifying…', 'show.run_verify': 'Run verification',
    'show.stale_plan': 'This plan is stale because the discovery snapshot or mapping changed. Generate a new plan.',
    'show.definition_locked': 'Discovery, mapping and new planning stay locked until the current execution is resumed and verified.', 'show.truncated': 'Only the first 500 items are shown here. The audit bundle contains the complete data.', 'show.reuse_warning': '{{type}} {{id}} differs in NetBox; reuse preserves the existing values.', 'show.schema_warning': 'NetBox did not expose write metadata for {{endpoint}}.',
    'show.use_sandbox': 'Use the internal disposable NetBox sandbox', 'show.change_target': 'Target-specific planning', 'show.change_target_help': 'After a verified rehearsal, refresh only the NetBox target and generate a new production-specific plan with the same source and mapping.', 'show.refresh_target': 'Refresh NetBox target',
    'conflict.target_field_constraint': 'A value violates a constraint reported by this NetBox version.', 'conflict.target_identity_collision': 'The resulting identity conflicts with another existing NetBox object.',
    'conflict.ambiguous_target': 'More than one NetBox object matches this source.', 'conflict.custom_field_mapping_type_conflict': 'Custom-field rules disagree on the target type.', 'conflict.custom_field_scope_mismatch': 'The existing custom field is not assigned to every required object type.', 'conflict.custom_field_type_mismatch': 'The existing custom field has an incompatible type.', 'conflict.dependency_cycle': 'The object dependencies contain a cycle.', 'conflict.duplicate_source_identity': 'The source contains a duplicate object identity.', 'conflict.duplicate_target_claim': 'Multiple source objects claim the same NetBox target.', 'conflict.invalid_custom_field_value': 'A custom-field value cannot be safely converted.', 'conflict.invalid_mapping': 'The mapping policy is invalid.', 'conflict.linked_target_missing': 'A previously linked NetBox object no longer exists.', 'conflict.linked_target_type_mismatch': 'A persistent object link points to the wrong NetBox type.', 'conflict.missing_dependency': 'A required source dependency is missing.', 'conflict.missing_identity': 'The source object has no safe migration identity.', 'conflict.target_required_field_missing': 'A field required by this NetBox version is missing.', 'conflict.target_write_schema_unavailable': 'NetBox did not confirm write compatibility for this mutation.', 'conflict.unsupported_target_choice': 'The mapped value is not accepted by this NetBox version.', 'conflict.unknown': 'Unknown blocking conflict.',
    'status.draft': 'Draft', 'status.discovering': 'Discovering', 'status.discovered': 'Discovered', 'status.planning': 'Planning', 'status.planned': 'Planned', 'status.approved': 'Approved', 'status.applying': 'Applying', 'status.applied': 'Applied', 'status.verifying': 'Verifying', 'status.verified': 'Verified', 'status.partially_applied': 'Partially applied', 'status.failed': 'Failed',
    'operation.create': 'Create', 'operation.reuse': 'Reuse', 'operation.update': 'Update', 'operation.ignore': 'Ignore',
    'execution.pending': 'Pending', 'execution.applying': 'Applying', 'execution.applied': 'Applied', 'execution.verifying': 'Verifying', 'execution.verified': 'Verified', 'execution.verification_failed': 'Verification failed', 'execution.failed': 'Failed',
  } },
  pt_BR: { translation: {
    'language.change': 'Alterar idioma', 'language.updating': 'Alterando idioma', 'common.back': 'Voltar aos projetos', 'common.create': 'Criar', 'common.status': 'Status',
    'welcome.title': 'Migre seu IPAM com segurança.', 'welcome.body': 'Descubra, mapeie, revise e aplique uma migração phpIPAM → NetBox com plano auditável.', 'welcome.setup': 'Configurar instalação', 'welcome.login': 'Entrar',
    'setup.title': 'Reivindicar instalação', 'setup.help': 'Use o token mostrado por', 'setup.token': 'Token', 'setup.name': 'Nome', 'setup.email': 'Email', 'setup.password': 'Senha', 'setup.password_help': '14–128 caracteres, com maiúscula, minúscula, número e símbolo.', 'setup.confirm': 'Confirmar senha', 'setup.submit': 'Criar owner',
    'login.title': 'Entrar no IpamFerry', 'login.submit': 'Entrar', 'dashboard.title': 'Projetos de migração', 'dashboard.new': 'Novo projeto', 'dashboard.empty': 'Crie um projeto para iniciar a descoberta.', 'dashboard.plans': '{{count}} plano(s) gerado(s)',
    'projects.new': 'Novo projeto', 'projects.name': 'Nome', 'projects.source': 'Origem', 'projects.existing': 'Projetos existentes', 'projects.api': 'API phpIPAM', 'projects.dump': 'mysqldump SQL', 'projects.locale': 'Idioma dos artefatos',
    'show.import': '1. Importar mysqldump', 'show.sql_safe': 'O SQL é analisado, nunca executado.', 'show.dump_file': 'Dump SQL', 'show.read_dump': 'Ler dump', 'show.discover': '1. Descobrir APIs', 'show.tokens_safe': 'Os tokens ficam apenas na memória do navegador e da requisição.', 'show.run_discovery': 'Executar descoberta', 'show.plan_apply': '4. Revisar, aprovar e aplicar', 'show.generate_plan': 'Gerar plano', 'show.actions_conflicts': '{{actions}} ações, {{conflicts}} conflitos', 'show.mapping_warning': '{{type}} requer revisão de mapeamento antes da exportação para o NetBox.', 'show.confirm_apply': 'Confirmo a aplicação deste plano exato e aprovado', 'show.apply': 'Aplicar via API', 'show.bundle': 'Baixar bundle auditável', 'show.netbox_url': 'URL NetBox', 'show.netbox_token': 'Token NetBox', 'show.phpipam_url': 'URL phpIPAM', 'show.phpipam_app': 'App ID', 'show.phpipam_token': 'Token phpIPAM',
    'show.inventory': '2. Inventário canônico', 'show.inventory_empty': 'Execute a descoberta para criar o inventário canônico sanitizado.', 'show.mapping': '3. Política de mapeamento', 'show.mapping_help': 'Escolha o idioma dos artefatos e edite a política versionada, sem código executável.', 'show.mapping_json': 'JSON de mapeamento', 'show.save_mapping': 'Salvar mapeamento', 'show.plan_help': 'O planejamento é somente leitura. Conflitos impedem aprovação e aplicação.', 'show.planning': 'Planejando…', 'show.conflicts': 'Conflitos impeditivos', 'show.actions': 'Ações planejadas', 'show.operation': 'Operação', 'show.source': 'Origem', 'show.target': 'Destino NetBox', 'show.identity': 'Chave natural', 'show.confirm_approve': 'Revisei o diff e aprovo este fingerprint exato', 'show.approve': 'Aprovar plano', 'show.applying': 'Aplicando lote…', 'show.resume': 'Retomar aplicação', 'show.execution': 'Execução #{{id}}', 'show.progress': '{{completed}} de {{total}} ações concluídas', 'show.verify': '5. Verificar estado do destino', 'show.verifying': 'Verificando…', 'show.run_verify': 'Executar verificação',
    'show.stale_plan': 'Este plano está desatualizado porque a descoberta ou o mapeamento mudou. Gere um novo plano.',
    'show.definition_locked': 'A descoberta, o mapeamento e um novo planejamento ficam bloqueados até a execução atual ser retomada e verificada.', 'show.truncated': 'Apenas os primeiros 500 itens aparecem aqui. O bundle auditável contém os dados completos.', 'show.reuse_warning': '{{type}} {{id}} difere no NetBox; a reutilização preserva os valores existentes.', 'show.schema_warning': 'O NetBox não expôs metadados de escrita para {{endpoint}}.',
    'show.use_sandbox': 'Usar o sandbox NetBox interno e descartável', 'show.change_target': 'Planejamento específico por destino', 'show.change_target_help': 'Após um ensaio verificado, redescubra apenas o destino NetBox e gere um novo plano específico para produção com a mesma origem e o mesmo mapeamento.', 'show.refresh_target': 'Redescobrir destino NetBox',
    'conflict.target_field_constraint': 'Um valor viola uma restrição informada por esta versão do NetBox.', 'conflict.target_identity_collision': 'A identidade resultante conflita com outro objeto existente no NetBox.',
    'conflict.ambiguous_target': 'Mais de um objeto do NetBox corresponde a esta origem.', 'conflict.custom_field_mapping_type_conflict': 'As regras de campo personalizado discordam sobre o tipo de destino.', 'conflict.custom_field_scope_mismatch': 'O campo personalizado existente não está atribuído a todos os tipos necessários.', 'conflict.custom_field_type_mismatch': 'O campo personalizado existente tem tipo incompatível.', 'conflict.dependency_cycle': 'As dependências dos objetos contêm um ciclo.', 'conflict.duplicate_source_identity': 'A origem contém uma identidade de objeto duplicada.', 'conflict.duplicate_target_claim': 'Vários objetos de origem reivindicam o mesmo destino no NetBox.', 'conflict.invalid_custom_field_value': 'Um valor de campo personalizado não pode ser convertido com segurança.', 'conflict.invalid_mapping': 'A política de mapeamento é inválida.', 'conflict.linked_target_missing': 'Um objeto do NetBox vinculado anteriormente não existe mais.', 'conflict.linked_target_type_mismatch': 'Um vínculo persistente aponta para o tipo errado no NetBox.', 'conflict.missing_dependency': 'Uma dependência obrigatória da origem está ausente.', 'conflict.missing_identity': 'O objeto de origem não tem identidade segura para migração.', 'conflict.target_required_field_missing': 'Falta um campo exigido por esta versão do NetBox.', 'conflict.target_write_schema_unavailable': 'O NetBox não confirmou compatibilidade de escrita para esta alteração.', 'conflict.unsupported_target_choice': 'O valor mapeado não é aceito por esta versão do NetBox.', 'conflict.unknown': 'Conflito impeditivo desconhecido.',
    'status.draft': 'Rascunho', 'status.discovering': 'Descobrindo', 'status.discovered': 'Descoberto', 'status.planning': 'Planejando', 'status.planned': 'Planejado', 'status.approved': 'Aprovado', 'status.applying': 'Aplicando', 'status.applied': 'Aplicado', 'status.verifying': 'Verificando', 'status.verified': 'Verificado', 'status.partially_applied': 'Parcialmente aplicado', 'status.failed': 'Falhou',
    'operation.create': 'Criar', 'operation.reuse': 'Reutilizar', 'operation.update': 'Atualizar', 'operation.ignore': 'Ignorar',
    'execution.pending': 'Pendente', 'execution.applying': 'Aplicando', 'execution.applied': 'Aplicado', 'execution.verifying': 'Verificando', 'execution.verified': 'Verificado', 'execution.verification_failed': 'Verificação falhou', 'execution.failed': 'Falhou',
  } },
  es: { translation: {
    'language.change': 'Cambiar idioma', 'language.updating': 'Cambiando idioma', 'common.back': 'Volver a proyectos', 'common.create': 'Crear', 'common.status': 'Estado',
    'welcome.title': 'Migra tu IPAM de forma segura.', 'welcome.body': 'Descubre, mapea, revisa y aplica una migración de phpIPAM a NetBox con un plan auditable.', 'welcome.setup': 'Configurar instalación', 'welcome.login': 'Iniciar sesión',
    'setup.title': 'Reclamar instalación', 'setup.help': 'Usa el token mostrado por', 'setup.token': 'Token', 'setup.name': 'Nombre', 'setup.email': 'Correo electrónico', 'setup.password': 'Contraseña', 'setup.password_help': '14–128 caracteres, con mayúscula, minúscula, número y símbolo.', 'setup.confirm': 'Confirmar contraseña', 'setup.submit': 'Crear propietario',
    'login.title': 'Iniciar sesión en IpamFerry', 'login.submit': 'Iniciar sesión', 'dashboard.title': 'Proyectos de migración', 'dashboard.new': 'Nuevo proyecto', 'dashboard.empty': 'Crea un proyecto para iniciar el descubrimiento.', 'dashboard.plans': '{{count}} plan(es) generado(s)',
    'projects.new': 'Nuevo proyecto', 'projects.name': 'Nombre', 'projects.source': 'Origen', 'projects.existing': 'Proyectos existentes', 'projects.api': 'API de phpIPAM', 'projects.dump': 'mysqldump SQL', 'projects.locale': 'Idioma de artefactos',
    'show.import': '1. Importar mysqldump', 'show.sql_safe': 'El SQL se analiza y nunca se ejecuta.', 'show.dump_file': 'Volcado SQL', 'show.read_dump': 'Leer volcado', 'show.discover': '1. Descubrir API', 'show.tokens_safe': 'Los tokens permanecen solo en la memoria del navegador y de la solicitud.', 'show.run_discovery': 'Ejecutar descubrimiento', 'show.plan_apply': '4. Revisar, aprobar y aplicar', 'show.generate_plan': 'Generar plan', 'show.actions_conflicts': '{{actions}} acciones, {{conflicts}} conflictos', 'show.mapping_warning': '{{type}} requiere revisión de mapeo antes de exportar a NetBox.', 'show.confirm_apply': 'Confirmo la aplicación de este plan exacto y aprobado', 'show.apply': 'Aplicar mediante API', 'show.bundle': 'Descargar bundle auditable', 'show.netbox_url': 'URL de NetBox', 'show.netbox_token': 'Token de NetBox', 'show.phpipam_url': 'URL de phpIPAM', 'show.phpipam_app': 'ID de aplicación', 'show.phpipam_token': 'Token de phpIPAM',
    'show.inventory': '2. Inventario canónico', 'show.inventory_empty': 'Ejecuta el descubrimiento para crear el inventario canónico saneado.', 'show.mapping': '3. Política de mapeo', 'show.mapping_help': 'Elige el idioma de los artefactos y edita la política versionada sin código ejecutable.', 'show.mapping_json': 'JSON de mapeo', 'show.save_mapping': 'Guardar mapeo', 'show.plan_help': 'La planificación es de solo lectura. Los conflictos impiden aprobar y aplicar.', 'show.planning': 'Planificando…', 'show.conflicts': 'Conflictos bloqueantes', 'show.actions': 'Acciones planificadas', 'show.operation': 'Operación', 'show.source': 'Origen', 'show.target': 'Destino NetBox', 'show.identity': 'Clave natural', 'show.confirm_approve': 'Revisé el diff y apruebo esta huella exacta', 'show.approve': 'Aprobar plan', 'show.applying': 'Aplicando lote…', 'show.resume': 'Reanudar aplicación', 'show.execution': 'Ejecución #{{id}}', 'show.progress': '{{completed}} de {{total}} acciones completadas', 'show.verify': '5. Verificar estado del destino', 'show.verifying': 'Verificando…', 'show.run_verify': 'Ejecutar verificación',
    'show.stale_plan': 'Este plan está desactualizado porque cambió el descubrimiento o el mapeo. Genera un plan nuevo.',
    'show.definition_locked': 'El descubrimiento, el mapeo y una nueva planificación permanecen bloqueados hasta reanudar y verificar la ejecución actual.', 'show.truncated': 'Aquí solo se muestran los primeros 500 elementos. El bundle de auditoría contiene todos los datos.', 'show.reuse_warning': '{{type}} {{id}} difiere en NetBox; la reutilización conserva los valores existentes.', 'show.schema_warning': 'NetBox no expuso metadatos de escritura para {{endpoint}}.',
    'show.use_sandbox': 'Usar el sandbox interno y desechable de NetBox', 'show.change_target': 'Planificación específica por destino', 'show.change_target_help': 'Después de un ensayo verificado, redescubre solo el destino NetBox y genera un nuevo plan específico para producción con el mismo origen y mapeo.', 'show.refresh_target': 'Actualizar destino NetBox',
    'conflict.target_field_constraint': 'Un valor infringe una restricción informada por esta versión de NetBox.', 'conflict.target_identity_collision': 'La identidad resultante entra en conflicto con otro objeto existente en NetBox.',
    'conflict.ambiguous_target': 'Más de un objeto de NetBox coincide con este origen.', 'conflict.custom_field_mapping_type_conflict': 'Las reglas de campos personalizados no coinciden en el tipo de destino.', 'conflict.custom_field_scope_mismatch': 'El campo personalizado existente no está asignado a todos los tipos requeridos.', 'conflict.custom_field_type_mismatch': 'El campo personalizado existente tiene un tipo incompatible.', 'conflict.dependency_cycle': 'Las dependencias de objetos contienen un ciclo.', 'conflict.duplicate_source_identity': 'El origen contiene una identidad de objeto duplicada.', 'conflict.duplicate_target_claim': 'Varios objetos de origen reclaman el mismo destino de NetBox.', 'conflict.invalid_custom_field_value': 'Un valor de campo personalizado no se puede convertir de forma segura.', 'conflict.invalid_mapping': 'La política de mapeo no es válida.', 'conflict.linked_target_missing': 'Un objeto de NetBox vinculado anteriormente ya no existe.', 'conflict.linked_target_type_mismatch': 'Un vínculo persistente apunta al tipo incorrecto de NetBox.', 'conflict.missing_dependency': 'Falta una dependencia requerida del origen.', 'conflict.missing_identity': 'El objeto de origen no tiene una identidad segura para migración.', 'conflict.target_required_field_missing': 'Falta un campo requerido por esta versión de NetBox.', 'conflict.target_write_schema_unavailable': 'NetBox no confirmó la compatibilidad de escritura para esta mutación.', 'conflict.unsupported_target_choice': 'El valor mapeado no es aceptado por esta versión de NetBox.', 'conflict.unknown': 'Conflicto bloqueante desconocido.',
    'status.draft': 'Borrador', 'status.discovering': 'Descubriendo', 'status.discovered': 'Descubierto', 'status.planning': 'Planificando', 'status.planned': 'Planificado', 'status.approved': 'Aprobado', 'status.applying': 'Aplicando', 'status.applied': 'Aplicado', 'status.verifying': 'Verificando', 'status.verified': 'Verificado', 'status.partially_applied': 'Parcialmente aplicado', 'status.failed': 'Falló',
    'operation.create': 'Crear', 'operation.reuse': 'Reutilizar', 'operation.update': 'Actualizar', 'operation.ignore': 'Ignorar',
    'execution.pending': 'Pendiente', 'execution.applying': 'Aplicando', 'execution.applied': 'Aplicado', 'execution.verifying': 'Verificando', 'execution.verified': 'Verificado', 'execution.verification_failed': 'La verificación falló', 'execution.failed': 'Falló',
  } },
} as const;

const fromDocument = (): LocaleCode => {
  if (typeof document === 'undefined') return 'en';
  const locale = document.documentElement.lang.toLowerCase();
  return locale === 'pt-br' ? 'pt_BR' : locale.startsWith('es') ? 'es' : 'en';
};

void i18n.use(initReactI18next).init({ resources, lng: fromDocument(), fallbackLng: 'en', interpolation: { escapeValue: false } });

export const isLocaleCode = (value: unknown): value is LocaleCode => localeCodes.includes(value as LocaleCode);
export const setDocumentLocale = (locale: LocaleCode): void => { if (typeof document !== 'undefined') document.documentElement.lang = locale === 'pt_BR' ? 'pt-BR' : locale; };
export const initializeLocaleSync = (): void => { router.on('navigate', event => { const locale = event.detail.page.props.locale; if (isLocaleCode(locale)) { void i18n.changeLanguage(locale); setDocumentLocale(locale); } }); };
export const useI18n = () => { const { t, i18n: instance } = useTranslation(); return { t, locale: isLocaleCode(instance.resolvedLanguage) ? instance.resolvedLanguage : 'en' as LocaleCode, changeLanguage: async (locale: LocaleCode) => { await instance.changeLanguage(locale); setDocumentLocale(locale); } }; };
