display_errors=Off
log_errors=On
upload_tmp_dir=/app/storage/framework/uploads
upload_max_filesize=1024M
post_max_size=1025M
max_file_uploads=1
max_input_time=3600
max_execution_time=180
default_socket_timeout=30
